# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    outputs:
      artifacts: ${{ steps.releaser.outputs.artifacts }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Run GoReleaser
      if: ${{ github.event_name != 'pull_request' }}
      id: releaser
      uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: release

    - name: Run GoReleaser
      if: ${{ github.event_name == 'pull_request' }}
      id: releaser
      uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: release --snapshot --clean
